# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flashback_home.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66lashback_home.proto\x12\x07youtube\"y\n\x14\x41\x63tivityListResponse\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x0c\n\x04\x65tag\x18\x02 \x01(\t\x12 \n\x05items\x18\x03 \x03(\x0b\x32\x11.youtube.Activity\x12#\n\x08pageInfo\x18\x04 \x01(\x0b\x32\x11.youtube.PageInfo\"\x86\x01\n\x08\x41\x63tivity\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x0c\n\x04\x65tag\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12!\n\x07snippet\x18\x04 \x01(\x0b\x32\x10.youtube.Snippet\x12/\n\x0e\x63ontentDetails\x18\x05 \x01(\x0b\x32\x17.youtube.ContentDetails\"\xf6\x01\n\x07Snippet\x12\x13\n\x0bpublishedAt\x18\x01 \x01(\t\x12\x11\n\tchannelId\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x34\n\nthumbnails\x18\x05 \x03(\x0b\x32 .youtube.Snippet.ThumbnailsEntry\x12\x14\n\x0c\x63hannelTitle\x18\x06 \x01(\t\x12\x0c\n\x04type\x18\x07 \x01(\t\x1a\x45\n\x0fThumbnailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.youtube.Thumbnail:\x02\x38\x01\"7\n\tThumbnail\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"1\n\x0e\x43ontentDetails\x12\x1f\n\x06upload\x18\x01 \x01(\x0b\x32\x0f.youtube.Upload\"\x19\n\x06Upload\x12\x0f\n\x07videoId\x18\x01 \x01(\t\"8\n\x08PageInfo\x12\x14\n\x0ctotalResults\x18\x01 \x01(\x05\x12\x16\n\x0eresultsPerPage\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flashback_home_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SNIPPET_THUMBNAILSENTRY._options = None
  _SNIPPET_THUMBNAILSENTRY._serialized_options = b'8\001'
  _ACTIVITYLISTRESPONSE._serialized_start=33
  _ACTIVITYLISTRESPONSE._serialized_end=154
  _ACTIVITY._serialized_start=157
  _ACTIVITY._serialized_end=291
  _SNIPPET._serialized_start=294
  _SNIPPET._serialized_end=540
  _SNIPPET_THUMBNAILSENTRY._serialized_start=471
  _SNIPPET_THUMBNAILSENTRY._serialized_end=540
  _THUMBNAIL._serialized_start=542
  _THUMBNAIL._serialized_end=597
  _CONTENTDETAILS._serialized_start=599
  _CONTENTDETAILS._serialized_end=648
  _UPLOAD._serialized_start=650
  _UPLOAD._serialized_end=675
  _PAGEINFO._serialized_start=677
  _PAGEINFO._serialized_end=733
# @@protoc_insertion_point(module_scope)
